"""
``genai-platform deploy <file.py>`` — Chapter 8's deploy CLI.

Walkthrough (matches the "Deploy walkthrough" section of the chapter-8 plan):

1. **Scan** — import the module, find every function with
   ``_workflow_metadata`` (set by ``@workflow``).
2. **Generate** — write artifacts into ``build/<workflow-name>/``:
   - ``Dockerfile`` (Listing 8.24)
   - ``Deployment.yaml`` + ``HorizontalPodAutoscaler.yaml`` + ``Service.yaml``
     populated from the decorator's scaling / resource fields. The CLI
     does **not** call ``kubectl`` — these are ready-to-apply artifacts
     for production K8s clusters.
   - A copy of the workflow's source file as ``workflow.py``.
3. **Build** — ``docker build -t genai-workflow/<name>:latest …``.
4. **Register + Deploy** — call ``WorkflowService.RegisterWorkflow`` then
   ``WorkflowService.DeployWorkflow`` over gRPC (via the SDK).
5. **Done** — print the curl one-liner the user runs to hit the workflow.

Local demo simplifications (chapter-8 plan, "Out of scope"): no image
registry push, no automatic rollback monitoring, ``kubectl`` is never
invoked. The K8s manifests work as a starting point for an adopter; the
local container runs via ``docker run`` from the Workflow Service.
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import shutil
import subprocess
import sys
import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

import yaml

from genai_platform.cli.docker_runner import DockerDeployer, _detect_compose_network

DEFAULT_GATEWAY_URL = "localhost:50051"
DEFAULT_GATEWAY_HTTP_URL = "http://localhost:8080"
RUNTIME_CONTAINER_PORT = 8000


@dataclass
class WorkflowItem:
    """A scanned ``@workflow`` function plus the source file it lives in."""

    function: Callable
    metadata: Dict[str, Any]
    source_file: Path


# ---- Scanning ---------------------------------------------------------------


def scan_for_workflows(source_path: Path) -> List[WorkflowItem]:
    """Import ``source_path`` and return every ``@workflow``-decorated function."""
    source_path = Path(source_path).resolve()
    spec = importlib.util.spec_from_file_location(
        f"_genai_workflow_{source_path.stem}", source_path
    )
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load module from {source_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    items: List[WorkflowItem] = []
    for value in vars(module).values():
        if callable(value) and hasattr(value, "_workflow_metadata"):
            items.append(
                WorkflowItem(
                    function=value,
                    metadata=dict(value._workflow_metadata),
                    source_file=source_path,
                )
            )
    return items


# ---- Dockerfile (Listing 8.24) ---------------------------------------------


def generate_dockerfile(item: WorkflowItem) -> str:
    """Return the Dockerfile text for one workflow.

    The build context is the repo root (so the Dockerfile can ``COPY``
    the SDK and the workflow source from the right places). The CLI sets
    that up in ``prepare_build_directory`` / ``build_image``.
    """
    name = item.metadata["name"]
    return textwrap.dedent(
        f"""\
        # Generated by genai-platform deploy. Listing 8.24.
        FROM python:3.12-slim

        # uv binary copied from the official Astral image for reproducible
        # locked installs (same pattern as docker/*.Dockerfile).
        COPY --from=ghcr.io/astral-sh/uv:0.11 /uv /usr/local/bin/

        WORKDIR /app

        # Install the SDK from the repo root build context. In production
        # this would be `uv pip install genai-platform==<version>` from PyPI.
        COPY pyproject.toml uv.lock README.md ./
        COPY genai_platform/ ./genai_platform/
        COPY proto/ ./proto/
        COPY services/ ./services/
        RUN uv sync --frozen --no-dev

        ENV PATH="/app/.venv/bin:$PATH"

        # Workflow source is staged into build/<name>/workflow.py by the CLI;
        # the build context root contains it at the staging path below.
        COPY build/{name}/workflow.py ./workflow.py

        ENV WORKFLOW_NAME={name}
        ENV WORKFLOW_MODULE=workflow
        ENV GENAI_GATEWAY_URL={DEFAULT_GATEWAY_URL}
        EXPOSE {RUNTIME_CONTAINER_PORT}

        CMD ["python", "-m", "genai_platform.runtime.server", "workflow"]
        """
    )


# ---- Kubernetes manifests --------------------------------------------------


def generate_kubernetes_manifests(item: WorkflowItem) -> Dict[str, str]:
    """Return ``{filename: yaml_text}`` for the Deployment / HPA / Service.

    Manifests reference ``genai-workflow/<name>:latest`` as the image name.
    Adopters retag/push for their registry, then ``kubectl apply -f`` the
    directory. The CLI never invokes ``kubectl``.
    """
    name = item.metadata["name"]
    image = f"genai-workflow/{name}:latest"
    api_path = item.metadata["api_path"]

    deployment = {
        "apiVersion": "apps/v1",
        "kind": "Deployment",
        "metadata": {
            "name": name,
            "labels": {"app": name, "genai-platform-workflow": "true"},
        },
        "spec": {
            "replicas": item.metadata["min_replicas"],
            "selector": {"matchLabels": {"app": name}},
            "template": {
                "metadata": {"labels": {"app": name}},
                "spec": {
                    "containers": [
                        {
                            "name": name,
                            "image": image,
                            "ports": [{"containerPort": RUNTIME_CONTAINER_PORT}],
                            "env": [
                                {"name": "WORKFLOW_NAME", "value": name},
                                {"name": "WORKFLOW_MODULE", "value": "workflow"},
                                {
                                    "name": "GENAI_GATEWAY_URL",
                                    "value": "gateway:50051",
                                },
                            ],
                            "resources": {
                                "limits": {
                                    "cpu": item.metadata["cpu"],
                                    "memory": item.metadata["memory"],
                                },
                                "requests": {
                                    "cpu": item.metadata["cpu"],
                                    "memory": item.metadata["memory"],
                                },
                            },
                            "livenessProbe": {
                                "httpGet": {
                                    "path": "/health/live",
                                    "port": RUNTIME_CONTAINER_PORT,
                                },
                                "initialDelaySeconds": 5,
                                "periodSeconds": 10,
                            },
                            "readinessProbe": {
                                "httpGet": {
                                    "path": "/health/ready",
                                    "port": RUNTIME_CONTAINER_PORT,
                                },
                                "initialDelaySeconds": 2,
                                "periodSeconds": 5,
                            },
                        }
                    ]
                },
            },
        },
    }

    hpa = {
        "apiVersion": "autoscaling/v2",
        "kind": "HorizontalPodAutoscaler",
        "metadata": {"name": name},
        "spec": {
            "scaleTargetRef": {
                "apiVersion": "apps/v1",
                "kind": "Deployment",
                "name": name,
            },
            "minReplicas": item.metadata["min_replicas"],
            "maxReplicas": item.metadata["max_replicas"],
            "metrics": [
                {
                    "type": "Resource",
                    "resource": {
                        "name": "cpu",
                        "target": {
                            "type": "Utilization",
                            "averageUtilization": item.metadata["target_cpu_percent"],
                        },
                    },
                }
            ],
        },
    }

    service = {
        "apiVersion": "v1",
        "kind": "Service",
        "metadata": {
            "name": name,
            "labels": {"app": name},
            "annotations": {"genai-platform/api-path": api_path},
        },
        "spec": {
            "selector": {"app": name},
            "ports": [
                {
                    "name": "http",
                    "port": 80,
                    "targetPort": RUNTIME_CONTAINER_PORT,
                }
            ],
        },
    }

    def dump(obj: dict) -> str:
        return yaml.safe_dump(obj, sort_keys=False)

    return {
        "Deployment.yaml": dump(deployment),
        "HorizontalPodAutoscaler.yaml": dump(hpa),
        "Service.yaml": dump(service),
    }


# ---- Build directory + Docker build ----------------------------------------


def prepare_build_directory(item: WorkflowItem, output_root: Optional[Path] = None) -> Path:
    """Stage Dockerfile + manifests + source copy under ``build/<name>/``.

    Returns the resulting build directory. Caller is responsible for
    invoking ``docker build`` afterwards.
    """
    name = item.metadata["name"]
    if output_root is None:
        output_root = repo_root() / "build"
    build_dir = output_root / name
    build_dir.mkdir(parents=True, exist_ok=True)

    (build_dir / "Dockerfile").write_text(generate_dockerfile(item))
    for filename, content in generate_kubernetes_manifests(item).items():
        (build_dir / filename).write_text(content)

    # Stage a renamed copy of the workflow source so the Dockerfile's COPY
    # line is stable. Original lives wherever the user pointed the CLI.
    shutil.copyfile(item.source_file, build_dir / "workflow.py")
    return build_dir


def build_image(build_dir: Path, image_tag: str) -> int:
    """Run ``docker build -t <image_tag> -f <Dockerfile> <repo_root>``.

    The build context is the repo root (so the SDK source can be COPYed
    in). Dockerfile lives inside ``build_dir``. Returns the subprocess
    return code.
    """
    if shutil.which("docker") is None:
        raise RuntimeError("`docker` not on PATH; install Docker to build images")
    cmd = [
        "docker",
        "build",
        "-t",
        image_tag,
        "-f",
        str(build_dir / "Dockerfile"),
        str(repo_root()),
    ]
    proc = subprocess.run(cmd)
    return proc.returncode


def repo_root() -> Path:
    """Find the repo root by walking up from CWD until pyproject.toml exists."""
    here = Path.cwd().resolve()
    for candidate in [here, *here.parents]:
        if (candidate / "pyproject.toml").exists():
            return candidate
    raise RuntimeError("Could not locate repo root (no pyproject.toml found)")


# ---- gRPC orchestration ----------------------------------------------------


def deploy_workflow(
    item: WorkflowItem,
    *,
    image_tag: str,
    gateway_url: str,
    skip_build: bool,
) -> None:
    """Generate artifacts → build image → register + deploy via gRPC."""
    from genai_platform import GenAIPlatform

    name = item.metadata["name"]
    print(f"\n--- {name} ---")
    build_dir = prepare_build_directory(item)
    print(f"  generated artifacts → {build_dir}")
    print("    Dockerfile, Deployment.yaml, HorizontalPodAutoscaler.yaml, Service.yaml")

    if skip_build:
        print("  --no-build: skipping `docker build`")
    else:
        print(f"  building image {image_tag}…")
        rc = build_image(build_dir, image_tag)
        if rc != 0:
            raise RuntimeError(f"`docker build` failed with code {rc}")
        print(f"  built {image_tag}")

    platform = GenAIPlatform(gateway_url=gateway_url)
    spec_proto = _spec_proto(item.metadata, image_tag)
    reg = platform.workflows._stub.RegisterWorkflow(
        _register_request(spec_proto), metadata=platform.workflows._metadata
    )
    print(f"  registered (workflow_id={reg.workflow_id}, version={reg.version})")

    if skip_build:
        print("  --no-build: skipping `docker run` and DeployWorkflow")
        return

    # CLI runs `docker run` itself — the Workflow Service has no docker
    # access. Then it reports the resulting container_id + endpoint to the
    # service via DeployWorkflow, which verifies /health/ready and
    # registers the route with the gateway.
    #
    # Pick the right gateway URL for the new container based on whether the
    # platform is running under docker compose or as bare host processes:
    #   - compose detected → container can resolve `gateway:50051` via DNS
    #   - host mode        → container reaches the host via host.docker.internal
    explicit = os.environ.get("GENAI_CONTAINER_GATEWAY_URL")
    if explicit:
        container_gateway_url = explicit
    elif _detect_compose_network():
        container_gateway_url = "gateway:50051"
    else:
        container_gateway_url = "host.docker.internal:50051"
    print("  launching container…")
    runner = DockerDeployer()
    try:
        result = runner.deploy(
            image=image_tag,
            name=item.metadata["name"],
            gateway_url=container_gateway_url,
        )
    except RuntimeError as e:
        raise SystemExit(f"  docker run failed: {e}") from e
    print(f"  container started (id={result.container_id[:12]}, endpoint={result.endpoint})")

    deploy_call = platform.workflows._stub.DeployWorkflow.with_call(
        _deploy_request(reg.workflow_id, reg.version, result.container_id, result.endpoint),
        metadata=platform.workflows._metadata,
    )
    deploy, call = deploy_call
    d = deploy.deployment
    print(f"  deployed (status={d.status}, endpoints={list(d.healthy_endpoints)})")

    if d.status != "healthy":
        details = call.details() or ""
        if details:
            print("\n  Deploy FAILED. Diagnostic from Workflow Service:")
            print("  " + details.replace("\n", "\n  "))
        # Surface container logs from the host (the CLI has docker access).
        logs = runner.container_logs(result.container_id)
        if logs:
            print("\n  Last container log lines:")
            print("  " + logs.replace("\n", "\n  "))
        return

    print(f"\nTry: curl -X POST {DEFAULT_GATEWAY_HTTP_URL}{item.metadata['api_path']} \\")
    print("       -H 'Content-Type: application/json' \\")
    print('       -d \'{"...": "..."}\'')


def _spec_proto(metadata: Dict[str, Any], image_tag: str):
    from proto import workflow_pb2

    return workflow_pb2.WorkflowSpec(
        name=metadata["name"],
        api_path=metadata["api_path"],
        container_image=image_tag,
        response_mode=metadata["response_mode"],
        scaling=workflow_pb2.ScalingConfig(
            min_replicas=metadata["min_replicas"],
            max_replicas=metadata["max_replicas"],
            target_cpu_percent=metadata["target_cpu_percent"],
        ),
        resources=workflow_pb2.ResourceConfig(
            cpu=metadata["cpu"],
            memory=metadata["memory"],
            gpu_type=metadata["gpu_type"],
            num_gpus=metadata["num_gpus"],
        ),
        reliability=workflow_pb2.ReliabilityConfig(
            timeout_seconds=metadata["timeout_seconds"],
            max_retries=metadata["max_retries"],
        ),
    )


def _register_request(spec):
    from proto import workflow_pb2

    return workflow_pb2.RegisterWorkflowRequest(spec=spec)


def _deploy_request(workflow_id: str, version: int, container_id: str, endpoint: str):
    from proto import workflow_pb2

    return workflow_pb2.DeployWorkflowRequest(
        workflow_id=workflow_id,
        version=version,
        container_id=container_id,
        endpoint=endpoint,
    )


# ---- CLI entry point -------------------------------------------------------


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="genai-platform",
        description="Deploy `@workflow`-decorated functions to the platform.",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    deploy = sub.add_parser("deploy", help="Deploy workflows from a Python file.")
    deploy.add_argument("source", help="Python file containing @workflow functions.")
    deploy.add_argument(
        "--gateway-url",
        default=DEFAULT_GATEWAY_URL,
        help=f"Gateway gRPC URL (default: {DEFAULT_GATEWAY_URL}).",
    )
    deploy.add_argument(
        "--no-build",
        action="store_true",
        help="Generate artifacts and register only; skip `docker build` and `DeployWorkflow`.",
    )

    args = parser.parse_args(argv)

    if args.command == "deploy":
        return _run_deploy(args)
    parser.error(f"Unknown command: {args.command}")
    return 2


def _run_deploy(args: argparse.Namespace) -> int:
    source_path = Path(args.source)
    if not source_path.exists():
        print(f"error: {source_path} does not exist", file=sys.stderr)
        return 2

    items = scan_for_workflows(source_path)
    if not items:
        print(f"No @workflow-decorated functions in {source_path}", file=sys.stderr)
        return 1

    print(f"Found {len(items)} workflow(s) in {source_path}")
    for item in items:
        image_tag = f"genai-workflow/{item.metadata['name']}:latest"
        deploy_workflow(
            item,
            image_tag=image_tag,
            gateway_url=args.gateway_url,
            skip_build=args.no_build,
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
