# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import observability_pb2 as observability__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in observability_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ObservabilityServiceStub(object):
    """Listing 7.1
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestLogs = channel.unary_unary(
                '/observability.ObservabilityService/IngestLogs',
                request_serializer=observability__pb2.IngestLogsRequest.SerializeToString,
                response_deserializer=observability__pb2.IngestLogsResponse.FromString,
                _registered_method=True)
        self.QueryLogs = channel.unary_unary(
                '/observability.ObservabilityService/QueryLogs',
                request_serializer=observability__pb2.QueryLogsRequest.SerializeToString,
                response_deserializer=observability__pb2.QueryLogsResponse.FromString,
                _registered_method=True)
        self.RecordMetrics = channel.unary_unary(
                '/observability.ObservabilityService/RecordMetrics',
                request_serializer=observability__pb2.RecordMetricsRequest.SerializeToString,
                response_deserializer=observability__pb2.RecordMetricsResponse.FromString,
                _registered_method=True)
        self.QueryMetrics = channel.unary_unary(
                '/observability.ObservabilityService/QueryMetrics',
                request_serializer=observability__pb2.QueryMetricsRequest.SerializeToString,
                response_deserializer=observability__pb2.QueryMetricsResponse.FromString,
                _registered_method=True)
        self.RecordSpan = channel.unary_unary(
                '/observability.ObservabilityService/RecordSpan',
                request_serializer=observability__pb2.RecordSpanRequest.SerializeToString,
                response_deserializer=observability__pb2.RecordSpanResponse.FromString,
                _registered_method=True)
        self.RecordGeneration = channel.unary_unary(
                '/observability.ObservabilityService/RecordGeneration',
                request_serializer=observability__pb2.RecordGenerationRequest.SerializeToString,
                response_deserializer=observability__pb2.RecordGenerationResponse.FromString,
                _registered_method=True)
        self.GetTrace = channel.unary_unary(
                '/observability.ObservabilityService/GetTrace',
                request_serializer=observability__pb2.GetTraceRequest.SerializeToString,
                response_deserializer=observability__pb2.Trace.FromString,
                _registered_method=True)
        self.QueryTraces = channel.unary_unary(
                '/observability.ObservabilityService/QueryTraces',
                request_serializer=observability__pb2.QueryTracesRequest.SerializeToString,
                response_deserializer=observability__pb2.QueryTracesResponse.FromString,
                _registered_method=True)
        self.RecordScore = channel.unary_unary(
                '/observability.ObservabilityService/RecordScore',
                request_serializer=observability__pb2.RecordScoreRequest.SerializeToString,
                response_deserializer=observability__pb2.RecordScoreResponse.FromString,
                _registered_method=True)
        self.QueryScores = channel.unary_unary(
                '/observability.ObservabilityService/QueryScores',
                request_serializer=observability__pb2.QueryScoresRequest.SerializeToString,
                response_deserializer=observability__pb2.QueryScoresResponse.FromString,
                _registered_method=True)
        self.GetCostReport = channel.unary_unary(
                '/observability.ObservabilityService/GetCostReport',
                request_serializer=observability__pb2.CostReportRequest.SerializeToString,
                response_deserializer=observability__pb2.CostReport.FromString,
                _registered_method=True)
        self.SetBudgetAlert = channel.unary_unary(
                '/observability.ObservabilityService/SetBudgetAlert',
                request_serializer=observability__pb2.SetBudgetAlertRequest.SerializeToString,
                response_deserializer=observability__pb2.SetBudgetAlertResponse.FromString,
                _registered_method=True)
        self.GetBudgetStatus = channel.unary_unary(
                '/observability.ObservabilityService/GetBudgetStatus',
                request_serializer=observability__pb2.GetBudgetStatusRequest.SerializeToString,
                response_deserializer=observability__pb2.BudgetStatus.FromString,
                _registered_method=True)
        self.GetServiceHealth = channel.unary_unary(
                '/observability.ObservabilityService/GetServiceHealth',
                request_serializer=observability__pb2.ServiceHealthRequest.SerializeToString,
                response_deserializer=observability__pb2.ServiceHealthResponse.FromString,
                _registered_method=True)


class ObservabilityServiceServicer(object):
    """Listing 7.1
    """

    def IngestLogs(self, request, context):
        """Logs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordMetrics(self, request, context):
        """Metrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordSpan(self, request, context):
        """Tracing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordGeneration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryTraces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordScore(self, request, context):
        """Scores
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryScores(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCostReport(self, request, context):
        """Cost & budgets
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBudgetAlert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBudgetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceHealth(self, request, context):
        """Health
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObservabilityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestLogs,
                    request_deserializer=observability__pb2.IngestLogsRequest.FromString,
                    response_serializer=observability__pb2.IngestLogsResponse.SerializeToString,
            ),
            'QueryLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryLogs,
                    request_deserializer=observability__pb2.QueryLogsRequest.FromString,
                    response_serializer=observability__pb2.QueryLogsResponse.SerializeToString,
            ),
            'RecordMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordMetrics,
                    request_deserializer=observability__pb2.RecordMetricsRequest.FromString,
                    response_serializer=observability__pb2.RecordMetricsResponse.SerializeToString,
            ),
            'QueryMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryMetrics,
                    request_deserializer=observability__pb2.QueryMetricsRequest.FromString,
                    response_serializer=observability__pb2.QueryMetricsResponse.SerializeToString,
            ),
            'RecordSpan': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordSpan,
                    request_deserializer=observability__pb2.RecordSpanRequest.FromString,
                    response_serializer=observability__pb2.RecordSpanResponse.SerializeToString,
            ),
            'RecordGeneration': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordGeneration,
                    request_deserializer=observability__pb2.RecordGenerationRequest.FromString,
                    response_serializer=observability__pb2.RecordGenerationResponse.SerializeToString,
            ),
            'GetTrace': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrace,
                    request_deserializer=observability__pb2.GetTraceRequest.FromString,
                    response_serializer=observability__pb2.Trace.SerializeToString,
            ),
            'QueryTraces': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryTraces,
                    request_deserializer=observability__pb2.QueryTracesRequest.FromString,
                    response_serializer=observability__pb2.QueryTracesResponse.SerializeToString,
            ),
            'RecordScore': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordScore,
                    request_deserializer=observability__pb2.RecordScoreRequest.FromString,
                    response_serializer=observability__pb2.RecordScoreResponse.SerializeToString,
            ),
            'QueryScores': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryScores,
                    request_deserializer=observability__pb2.QueryScoresRequest.FromString,
                    response_serializer=observability__pb2.QueryScoresResponse.SerializeToString,
            ),
            'GetCostReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCostReport,
                    request_deserializer=observability__pb2.CostReportRequest.FromString,
                    response_serializer=observability__pb2.CostReport.SerializeToString,
            ),
            'SetBudgetAlert': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBudgetAlert,
                    request_deserializer=observability__pb2.SetBudgetAlertRequest.FromString,
                    response_serializer=observability__pb2.SetBudgetAlertResponse.SerializeToString,
            ),
            'GetBudgetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBudgetStatus,
                    request_deserializer=observability__pb2.GetBudgetStatusRequest.FromString,
                    response_serializer=observability__pb2.BudgetStatus.SerializeToString,
            ),
            'GetServiceHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceHealth,
                    request_deserializer=observability__pb2.ServiceHealthRequest.FromString,
                    response_serializer=observability__pb2.ServiceHealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'observability.ObservabilityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('observability.ObservabilityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ObservabilityService(object):
    """Listing 7.1
    """

    @staticmethod
    def IngestLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/observability.ObservabilityService/IngestLogs',
            observability__pb2.IngestLogsRequest.SerializeToString,
            observability__pb2.IngestLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/observability.ObservabilityService/QueryLogs',
            observability__pb2.QueryLogsRequest.SerializeToString,
            observability__pb2.QueryLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/observability.ObservabilityService/RecordMetrics',
            observability__pb2.RecordMetricsRequest.SerializeToString,
            observability__pb2.RecordMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/observability.ObservabilityService/QueryMetrics',
            observability__pb2.QueryMetricsRequest.SerializeToString,
            observability__pb2.QueryMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordSpan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/observability.ObservabilityService/RecordSpan',
            observability__pb2.RecordSpanRequest.SerializeToString,
            observability__pb2.RecordSpanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordGeneration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/observability.ObservabilityService/RecordGeneration',
            observability__pb2.RecordGenerationRequest.SerializeToString,
            observability__pb2.RecordGenerationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/observability.ObservabilityService/GetTrace',
            observability__pb2.GetTraceRequest.SerializeToString,
            observability__pb2.Trace.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryTraces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/observability.ObservabilityService/QueryTraces',
            observability__pb2.QueryTracesRequest.SerializeToString,
            observability__pb2.QueryTracesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/observability.ObservabilityService/RecordScore',
            observability__pb2.RecordScoreRequest.SerializeToString,
            observability__pb2.RecordScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryScores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/observability.ObservabilityService/QueryScores',
            observability__pb2.QueryScoresRequest.SerializeToString,
            observability__pb2.QueryScoresResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCostReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/observability.ObservabilityService/GetCostReport',
            observability__pb2.CostReportRequest.SerializeToString,
            observability__pb2.CostReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetBudgetAlert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/observability.ObservabilityService/SetBudgetAlert',
            observability__pb2.SetBudgetAlertRequest.SerializeToString,
            observability__pb2.SetBudgetAlertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBudgetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/observability.ObservabilityService/GetBudgetStatus',
            observability__pb2.GetBudgetStatusRequest.SerializeToString,
            observability__pb2.BudgetStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServiceHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/observability.ObservabilityService/GetServiceHealth',
            observability__pb2.ServiceHealthRequest.SerializeToString,
            observability__pb2.ServiceHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
